DROP DATABASE IF EXISTS smart;
CREATE DATABASE smart DEFAULT CHARACTER SET UTF8;
use smart;
CREATE TABLE user (
  id int AUTO_INCREMENT PRIMARY KEY,
  username varchar(20) NOT NULL UNIQUE,
  password VARBINARY(20) NOT NULL
)

